### ISSUE TITLE
Compile regex

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [HuehueJS/common-lang#3]
https://github.com/HuehueJS/common-lang/blob/d17f4aa86016a70bff0911cb85e4a6f99f2b6474/src/case-converter/name-convention-splitter/camel.splitter.js#L9

That isn't a good place to compile the regex, should be at the constructor

**Comment by rafaelim** [comment]
how did you delete this file, i guess this issue doesn't exist more.
