### ISSUE TITLE
Possible error

### ISSUE THREAD

**Issue by rafaelim** [HuehueJS/common-lang#5]
https://github.com/HuehueJS/common-lang/blob/350093232c670787996ab2d4a2fc3399c6b4b569/src/main.js#L22#L24
`    if (obj === undefined || obj === null) {
        return defaultValue;
    }`
what should return in this if??

**Comment by ettoreleandrotognoli** [comment]
return the defaultValue parameter no?

**Comment by rafaelim** [comment]
function doesn't have a defaultValue and it's a set function, for me a set function doesn't return anything.

**Comment by ettoreleandrotognoli** [comment]
ow o.o
I thought was the getattr function

**Comment by rafaelim** [comment]
is this already done?

**Comment by ettoreleandrotognoli** [comment]
I think so
